version: '3'

services:
    mongo:
        image: mongo:latest
        restart: always
        container_name: mongodb
        ports:
            - 27031:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - ./:/var/www/html
        networks:
            sql-app-network:
                ipv4_address: 10.0.0.8


networks:
    sql-app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.0.0.0/16"