version: '3'

services:
    postgres:
        image: postgres
        restart: always
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./dataPgsql/db:/var/lib/postgresql/data
        networks:
            gus-laravel-network:
                ipv4_address: 12.0.0.7


networks:
    sql-app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "11.0.0.0/16"