version: '3'

services:
    mysql:
        image: mysql:8.0
        restart: always
        container_name: sqlstudy
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: laravel
        volumes:
            - ./dockerDBData:/var/lib/mysql
            - ./data:/var/www
        networks:
            sql-app-network:
                ipv4_address: 10.0.0.8

    api:
        build:
            context: .
            dockerfile: ubuntu.dockerfile
        ports:
            - 84:80
        volumes:
            - ./:/var/www/html
        container_name: api
        networks:
            sql-app-network:
                ipv4_address: 10.0.0.9

networks:
    sql-app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.0.0.0/16"